import type { Metadata } from "next";
import {italianno, roboto,manrope} from "@/app/ui/fonts";
import "@/app/ui/global.css";
import Header from "./ui/header";
import Footer from "./ui/Footer";
import { ToastContainer } from 'react-toastify';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${italianno.variable} ${roboto.variable} ${manrope.variable} antialiased`}>
        <Header/>
        {children} 
        <Footer/>
        <ToastContainer />
        </body>
    </html>
  );
}
